### ISSUE TITLE
Unable to run proxy server Unexpected token ... ???

### ISSUE THREAD

**Issue by jonnym1** [ayastreb/bandwidth-hero-proxy#10]
Anybody know what i'm doing wrong?

`/root/bandwidth-hero-proxy-master/src/proxy.js:14
        ...pick(req.headers, ['cookie', 'dnt', 'referer']),
        ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/root/bandwidth-hero-proxy-master/server.js:5:15)
`

**Comment by jonnym1** [comment]
Problem solved, Was running an old version of nodeJS.
Thanks.
