### ISSUE TITLE
Error when running server.js

### ISSUE THREAD

**Issue by emmauss** [ayastreb/bandwidth-hero-proxy#11]
i get this error when running the server
/root/boost/bandwidth-hero-proxy/src/proxy.js:14
      ...pick(req.headers, ['cookie', 'dnt', 'referer']),
      ^^^
SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/root/boost/bandwidth-hero-proxy/server.js:6:15)

I have installed node.js and npm

**Comment by ayastreb** [comment]
Hi! Which version of node.js do you have? it requires at least 8.6.0

**Comment by emmauss** [comment]
I followed the guide in the readme, so it should install the latest version. apt shows version as 6.11

**Comment by emmauss** [comment]
updated to 9.4, now working
